### ISSUE TITLE
Repeated header image in aDDDvent calendar article

### ISSUE THREAD

**Issue by sitek94** [ducin/ducin.dev#5]
Cześć Tomasz! Brałem udział w ANFie jakiś czas temu i od tamtego czasu Cię obserwuję i dzięki temu rzuciła mi się w oczy nowa seria aDDDvent calendar, swoją drogą świetna nazwa :D

Nie wiem czy już zauważyłeś, ale na większych ekranach (`> 1500px`) zaczyna powtarzać się header image:

![Arc 2024-12-01 17 59 47](https://github.com/user-attachments/assets/569cd19e-386b-4639-9696-1575772dfb52)

Prawdopodobnie, bo background shorthand nadpisuje poprzednie style:

![Arc 2024-12-01 18 01 47](https://github.com/user-attachments/assets/2dd6951e-b71f-449b-bb48-731e4243fe54)

Mam nadzieję, że to pomoże :) 

Tymczasem, czekam na kolejne artykuły z serii, dzięki!

**Comment by ducin** [comment]
cześć @sitek94 !

Ja w CSSy jestem taki jak widzisz 😅 Za drugim podejściem znalazłem miejsce, gdzie można to poprawić skutecznie. Rozumiem, że `background` nadpisywało hurtem wszystko -> `repeat` i `size` też się zszczyściły. A teraz -> nie.

Dzięki! Gdybyś w trakcie czytania miał kolejne sugestie to z przyjemnością przyjmę ;)

EDIT: kurczę, a jednak coś mi się wywaliło... wdrażam "hotfix" :P
<img width="2464" alt="image" src="https://github.com/user-attachments/assets/790af6cd-c427-4e46-96c1-7eefb3ba2c8b">

**Comment by sitek94** [comment]
Dokładnie, tam właśnie background shorthand nadpisywał wszystko, a jeszcze się wywaliło później, bo na głównym headerze jest `background-attachment: fixed` :D 

Teraz wszystko jest cacy, ale to tam szczegóły, ważne, że artykuły się pojawiają!
